# Project SQL: Data Discovery with the Chinook Database

Welcome to your first major hands-on data exploration project. In this assignment, you will be stepping into the role of a data analyst querying the Chinook database: a sample dataset representing a digital media store, complete with information about artists, albums, tracks, customers, and business sales.

The core objective of this project is to transition you from simply writing code to thinking like a data scientist. To do that, our journey follows a deliberate, four-fold progression:

### Phase 1. Master the Mechanics (Get Familiar with SQL)

Before you can extract deep insights, you need to speak the language. You will start by practicing the fundamental mechanics of SQL using the SQL statements below: learning how to filter data, join tables, group metrics, and aggregate numbers. Think of this as learning how to move around the data environment smoothly.  As a starting point, pick a single table and answer the "How many ...?" questions using SQL.  Then repeat the process for each table.

### Phase 2. Map the Terrain (Get Familiar with the Data)

Data never exists in a vacuum. By writing queries, you will uncover the shape, structure, and quirks of the Chinook dataset. Again, using the SQL statements below, you'll learn how the tables relate to one another, what a single row represents in different contexts, and where specific types of information live.  Here's where you should get familiar with the ERD and join tables in various ways.

### Phase 3. Answer Guided Questions

Once you know the syntax and understand the data structure, you will put your skills to work solving specific business problems. Below are sets of explicit questions to answer using SQL. This phase mimics standard reporting: you are handed a specific prompt, and your job is to translate that prompt into an accurate, data-driven answer.

Here are some practice questions:
- https://github.com/LucasMcL/15-sql_queries_02-chinook/blob/master/README.md
- [Using the R language]( https://rpubs.com/enext777/636199 )
- [Search Google]( https://www.google.com/search?q=chinook+database+questions )
- Ask AI to generate some questions for you.  Be sure to mention the Chinook data set.

### Phase 4. Ask and Answer Your Own Questions

This final phase is the most critical part of the project. The true hallmark of a great data scientist isn't just answering the questions you're handed; it's having the curiosity and intuition to formulate your own questions.

You are tasked with looking at the Chinook dataset, generating your own original hypotheses or business questions, and writing the SQL required to answer them.

Demonstrate that you know SQL fundamentals by posting a question for each SQL statement below and then using the SQL statement to answer you question.

You will use the material from this phase for the presentation.

## Why This Matters: The Path to Your Capstone

Learning to ask your own questions is the exact skill you will rely on for your final capstone project. In your capstone, you will choose a dataset from your own field of interest. No one will hand you a list of prompts or a guide telling you what to look for.

Use this project as your sandbox. Mastering the ability to interrogate a database now will give you the framework you need to discover meaningful, independent insights in your capstone later.

## Chinook data set

See the lecture on SQLite3 using the Chinook data set to set up the software, database, and tables, as well as for the links to ancillary information about the data set.

In [2]:
%%bash
# Install the sqlite package for Ubuntu-2ubuntu0.6_amd64.
apt-get -qq update
# Download the Chinook sqlite database   /libsqlite3-dev_3.37.2
apt-get -qq install -y sqlite3
# load the zip file and unzip
[ -f chinook.zip ] || curl -s -O https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
unzip -u chinook.zip
ls -la chinook.db

(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../libsqlite3-dev_3.37.2-2ubuntu0.6_amd64.deb ...
Unpacking libsqlite3-dev:amd64 (3.37.2-2ubuntu0.6) over (3.37.2-2ubuntu0.5) ...
Preparing to unpack .../libsqlite3-0_3.37.2-2ubuntu0.6_amd64.deb ...
Unpacking libsqlite3-0:amd64 (3.37.2-2ubuntu0.6) over (3.37.2-2ubuntu0.5) ...
Selecting previously unselected package sqlite3.
Preparing to unpack .../sqlite3_3.37.2-2ubuntu0.6_amd64.deb ...
Unpacking sqlite3 (3.37.2-2ubuntu0.6) ...
Setting up libsqlite3-0:amd64 (3.37.2-2ubuntu0.6) ...
Setting up libsqlite3-dev:amd64 (3.37.2-2ubuntu0.6) ...
Setting up sqlite3 (3.37.2-2ubuntu0.6) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

Archive:  chinook.zip
  inflating: chinook.db
-rw-r--r-- 1 root root 884736 Nov 29  2015 chinook.db

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

## Use SQL queries to pull specific information

Do NOT pull all the data and then filter using DataFrame methods.  The initial purpose is to get familiar with SQL.

In [3]:
import sqlite3 as db
import pandas as pd
from contextlib import closing

### Identifying what is in the database - there are 11 tables, albums, artist, customer etc.

In [4]:
 # 11 tables # the internal catalogue of SQLITE - help
# excluding sqllite indexing, triggers and views # sorting by alphabetical order without modificaiton
query = """
  SELECT name
  FROM sqlite_master
  WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
  ORDER BY name;
"""
with closing(db.connect("chinook.db")) as db_con:
    tables = pd.read_sql_query(query, db_con)

tables

              name
0           albums
1          artists
2        customers
3        employees
4           genres
5    invoice_items
6         invoices
7      media_types
8   playlist_track
9        playlists
10          tracks

### Basic Queries

#### SELECT (with * and with column names)

### Identifying the all the column names in media type using SELECT wildcard * - MOEG, AAC, MEPEG 4

In [5]:
query = """

   SELECT *

  FROM media_types

  LIMIT 10;
"""
with closing(db.connect("chinook.db")) as db_con:
  df = pd.read_sql_query(query, db_con)
df

   MediaTypeId                         Name
0            1              MPEG audio file
1            2     Protected AAC audio file
2            3  Protected MPEG-4 video file
3            4     Purchased AAC audio file
4            5               AAC audio file

### Call table Media_Type and Media_Type Id with corresponding format types in row names

In [17]:
query = """

  Select MediaTypeId, Name

  FROM media_types

  LIMIT 10;

"""

with closing(db.connect("chinook.db")) as db_con:
  df = pd.read_sql_query(query, db_con)

df

   MediaTypeId                         Name
0            1              MPEG audio file
1            2     Protected AAC audio file
2            3  Protected MPEG-4 video file
3            4     Purchased AAC audio file
4            5               AAC audio file

#### WHERE

### Query table invoices and use Select * (wildcard) to identify the names of columns - limited 10 and closed query at the end of the query there are 9 columns InvoiceID, customer id invoice date, billing rows and total. Limit 10 starts at 0.

In [7]:
query = """

   SELECT *

  FROM invoices

  LIMIT 10;
"""
with closing(db.connect("chinook.db")) as db_con:
  df = pd.read_sql_query(query, db_con)
df

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,2,4,2009-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96
2,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94
3,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
5,6,37,2009-01-19 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,0.99
6,7,38,2009-02-01 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,1.98
7,8,40,2009-02-01 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,1.98
8,9,42,2009-02-02 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,3.96
9,10,46,2009-02-03 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,5.94

### Used Select to call Invoice date columns and where in Invvoicedate to determine which date begin in 2010 - limited 10.  Dates start with Year month, and day with time equaling 00.00.00,

In [18]:
#

query = """

  SELECT InvoiceDate

  FROM invoices

  WHERE  Invoicedate LIKE '2010%'

  LIMIT 10;

"""
with closing(db.connect("chinook.db")) as db_con:
    df = pd.read_sql_query(query, db_con)
df

           InvoiceDate
0  2010-01-08 00:00:00
1  2010-01-08 00:00:00
2  2010-01-09 00:00:00
3  2010-01-10 00:00:00
4  2010-01-13 00:00:00
5  2010-01-18 00:00:00
6  2010-01-26 00:00:00
7  2010-02-08 00:00:00
8  2010-02-08 00:00:00
9  2010-02-09 00:00:00

Used string format time which temporary converts the date time format - only used to practice in this exercise - not good for large databases - slows the query.  Extracted the year 2013 - tried 2015 but query returned no values.  Wanted to know what the last year in the table was - answer 2013

In [21]:
query = """

  SELECT InvoiceDate

  FROM invoices

  WHERE  strftime('%Y', Invoicedate) = "2013"

  LIMIT 15;

"""
with closing(db.connect("chinook.db")) as db_con:
    df = pd.read_sql_query(query, db_con)
df

            InvoiceDate
0   2013-01-02 00:00:00
1   2013-01-07 00:00:00
2   2013-01-15 00:00:00
3   2013-01-28 00:00:00
4   2013-01-28 00:00:00
5   2013-01-29 00:00:00
6   2013-01-30 00:00:00
7   2013-02-02 00:00:00
8   2013-02-07 00:00:00
9   2013-02-15 00:00:00
10  2013-02-28 00:00:00
11  2013-02-28 00:00:00
12  2013-03-01 00:00:00
13  2013-03-02 00:00:00
14  2013-03-05 00:00:00

#### AND

### Select for Billing city, custoemr id, and total - from invoices table, wanted to dettermine how many customer ids in Stuttgarts between the customer Id range of 20 and 37 = result = no customers in Stuttgart with customer IDs betwen 20 and 37

In [37]:
query = """

  SELECT BillingCity, CustomerId, TOTAL

  FROM invoices

  WHERE  BillingCity = 'Stuttgart'

    AND CustomerId Between 20 AND 37

  LIMIT 15;

"""
with closing(db.connect("chinook.db")) as db_con:
    df = pd.read_sql_query(query, db_con)
df

Empty DataFrame
Columns: [BillingCity, CustomerId, Total]
Index: []

### See how many customers in range of 4 to 20 who spent more than $5.00 dollars

In [51]:
query = """

  SELECT BillingCity, CustomerId, TOTAL

  FROM invoices

  WHERE CustomerId Between 4 AND 100

  AND TOTAL > 2.00

  LIMIT 25;

"""
with closing(db.connect("chinook.db")) as db_con:
    df = pd.read_sql_query(query, db_con)
df

   BillingCity  CustomerId  Total
0         Oslo           4   3.96
1         Oslo           4   5.94
2         Oslo           4  15.86
3         Oslo           4   8.91
4       Prague           5   3.96
5       Prague           5   5.94
6       Prague           5  16.86
7       Prague           5   8.91
8       Prague           6   8.91
9       Prague           6   3.96
10      Prague           6   5.94
11      Prague           6  25.86
12      Vienne           7  18.86
13      Vienne           7   8.91
14      Vienne           7   3.96
15      Vienne           7   5.94
16    Brussels           8   5.94
17    Brussels           8  13.86
18    Brussels           8   8.91
19    Brussels           8   3.96
20  Copenhagen           9   3.96
21  Copenhagen           9   5.94
22  Copenhagen           9  13.86
23  Copenhagen           9   8.91
24   São Paulo          10   8.91

#### OR

In [52]:
query = """

  SELECT BillingCity, BillingPostalCode,  TOTAL

  FROM invoices

  WHERE  BillingCity = 'Stuttgart' OR 'Frankfurt'
   AND BillingPostalCode = '70174'
    OR BillingState IS NULL

  LIMIT 15;

"""
with closing(db.connect("chinook.db")) as db_con:
    df = pd.read_sql_query(query, db_con)
df

   BillingCity BillingPostalCode  Total
0    Stuttgart             70174   1.98
1         Oslo              0171   3.96
2     Brussels              1000   5.94
3    Frankfurt             60316   0.99
4       Berlin             10779   1.98
5        Paris             75002   1.98
6     Bordeaux             33000   3.96
7       London            N1 5LH   8.91
8    Stuttgart             70174  13.86
9        Paris             75002  13.86
10  Edinburgh            EH4 1HH   0.99
11    Santiago              None   1.98
12   Bangalore            560001   3.96
13        Oslo              0171   5.94
14      Lisbon              None   1.98

#### LIKE (with % or _ wildcard)

In [14]:
query = """

  SELECT BillingCity, BillingPostalCode, BillingState, TOTAL

  FROM invoices

  WHERE  BillingCity = 'Stuttgart' OR 'Frankfurt'
   AND BillingPostalCode = '70174'
    OR BillingState LIKE '_A'

  LIMIT 15;

"""
with closing(db.connect("chinook.db")) as db_con:
    df = pd.read_sql_query(query, db_con)
df

      BillingCity BillingPostalCode BillingState  Total
0       Stuttgart             70174         None   1.98
1          Boston              2113           MA  13.86
2       Stuttgart             70174         None  13.86
3   Mountain View        94043-1351           CA   0.99
4         Redmond        98052-8300           WA   1.98
5       Cupertino             95014           CA   1.98
6       Cupertino             95014           CA  13.86
7         Redmond        98052-8300           WA   3.96
8         Redmond        98052-8300           WA   5.94
9          Boston              2113           MA   8.91
10      Stuttgart             70174         None   8.91
11      Cupertino             95014           CA   8.91
12        Redmond        98052-8300           WA   0.99
13  Mountain View         94040-111           CA   1.98
14  Mountain View         94040-111           CA  13.86

#### BETWEEN

#### LIMIT

### Sorting and Grouping

#### ORDER BY

#### DISTINCT

#### GROUP BY

### Aggregates

#### MAX

#### MIN

#### SUM

#### AVG

#### COUNT

## Make some plots

Make some cool plots to go with your data. Write SQL queries to get ONLY the information you need for each plot. (Don't pull ALL the data and then just plot a few columns.)

## EXTRA CREDIT:
* Use a CTE
* Use a query that joins two or more tables.
* Make a model to see if you can predict something ( e.g. GNB classifier, linear regression )
* Come up with something else cool to do with your data