<a href="https://colab.research.google.com/github/cyeef/Data-Science-Portfolio-C21-/blob/main/Projects/Project-3/SQL.2-BQ.project.template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project SQL - BigQuery

## Pick a dataset that interests you (or multiple data sets)

Use the Open Data Sets available from Google BigQuery. You can use your own Google account or Kaggle.

## Come up with questions about your data
* What sort of information is in this dataset?
* How many records are there?
* Have the number of bitcoin transactions increased year over year?
* Does New Mexico get more or less rain now than 20 years ago?
* How many different countries (states, counties, cities, etc) have records in this data set?

## Use SQL queries to pull specific information

Like with the Chinook data base, do NOT pull all the data and then filter using DataFrame methods etc.

Write your question and then answer it using the SQL statements below.  Be sure to use guardrails ( e.g. dryrun ).

### Basic Queries

## Using usa_1910_Current for table storage stats

* Number of rows
  * 6,311,504
* Total logical bytes
  * 185.85 MB
* Active logical bytes
  * 0 B
* Long term logical bytes
  * 185.85 MB
* Current physical bytes
  * 12.05 MB
* Total physical bytes
  * 12.05 MB
* Active physical bytes
  * 0 B
* Long term physical bytes
  * 12.05 MB
* Time travel physical bytes
  * 0 B

Access Big Query big-pops account

In [1]:
from google.colab import auth
auth.authenticate_user()

project_id = "big-pops-501222"   # my project id

from google.cloud import bigquery
client = bigquery.Client(project=project_id)
print("Connected to project:", project_id)

Connected to project: big-pops-501222

### Dry run no charge = False if go over means fail to query

In [12]:
def dry_run(query):
    """Estimate bytes scanned WITHOUT running the query. No charge."""
    job_config = bigquery.QueryJobConfig(dry_run=True, use_query_cache=False)
    job = client.query(query, job_config=job_config)
    gb = job.total_bytes_processed / 1e9
    print(f"This query will scan {job.total_bytes_processed:,} bytes ({gb:.4f} GB)")
    return job.total_bytes_processed

Max 1.0 GB = No charge

In [14]:
def run_sql(query, max_gb=1.0):
    cfg = bigquery.QueryJobConfig(maximum_bytes_billed=int(max_gb * 1e9))
    return client.query(query, job_config=cfg).to_dataframe()

#### SELECT (with * and with column names)

## Used Select * to view table From `bigquery-public-data.usa_names.usa_1910_current`

In [15]:
query = """
    SELECT *
    FROM `bigquery-public-data.usa_names.usa_1910_current`

    LIMIT 10
"""

dry_run(query)          # check bytes — should be tiny
df = run_sql(query)   # then run
df

This query will scan 194,873,810 bytes (0.1949 GB)

  state gender  year      name  number
0    AK      F  1910      Mary      14
1    AK      F  1910     Annie      12
2    AK      F  1910      Anna      10
3    AK      F  1910  Margaret       8
4    AK      F  1910     Helen       7
5    AK      F  1910     Elsie       6
6    AK      F  1910      Lucy       6
7    AK      F  1910   Dorothy       5
8    AK      F  1911      Mary      12
9    AK      F  1911  Margaret       7

Used Select with name, gender, year, and number from `bigquery-public-data.usa_names.usa_1910_current` List of names, females ,and total name counts  -  ran and got 5 columns had to press shift + enteer to get this cell to run without getting the state results

In [20]:
query = """

  SELECT name, gender, year, number
    FROM `bigquery-public-data.usa_names.usa_1910_current`
  LIMIT 10
"""



dry_run(query)
df = run_sql(query)
df

This query will scan 169,627,794 bytes (0.1696 GB)

       name gender  year  number
0      Mary      F  1910      14
1     Annie      F  1910      12
2      Anna      F  1910      10
3  Margaret      F  1910       8
4     Helen      F  1910       7
5     Elsie      F  1910       6
6      Lucy      F  1910       6
7   Dorothy      F  1910       5
8      Mary      F  1911      12
9  Margaret      F  1911       7

#### WHERE

### WHERE to select gender female

In [23]:
query = """
    SELECT name, gender, year, number, state
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE gender = 'F'
    LIMIT 30
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 194,873,810 bytes (0.1949 GB)

         name gender  year  number state
0        Mary      F  1910      14    AK
1       Annie      F  1910      12    AK
2        Anna      F  1910      10    AK
3    Margaret      F  1910       8    AK
4       Helen      F  1910       7    AK
5       Elsie      F  1910       6    AK
6        Lucy      F  1910       6    AK
7     Dorothy      F  1910       5    AK
8        Mary      F  1911      12    AK
9    Margaret      F  1911       7    AK
10       Ruth      F  1911       7    AK
11      Annie      F  1911       6    AK
12  Elizabeth      F  1911       6    AK
13      Helen      F  1911       6    AK
14       Mary      F  1912       9    AK
15      Elsie      F  1912       8    AK
16      Agnes      F  1912       7    AK
17       Anna      F  1912       7    AK
18      Helen      F  1912       7    AK
19     Louise      F  1912       7    AK
20       Jean      F  1912       6    AK
21       Ruth      F  1912       6    AK
22      Alice      F  1912       5    AK
23     Esther      F  1912       5    AK
24      Ethel      F  1912       5    AK
25   Margaret      F  1912       5    AK
26      Marie      F  1912       5    AK
27       Mary      F  1913      21    AK
28  Elizabeth      F  1913       9    AK
29   Margaret      F  1913       8    AK

#### AND

Using where gender is female and is state NM the use of and where must be true to return results

In [24]:
query = """
    SELECT name, gender, year, number, state
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE gender = 'F' AND state = 'NM'
    LIMIT 30
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 194,873,810 bytes (0.1949 GB)

         name gender  year  number state
0        Mary      F  1910      98    NM
1       Maria      F  1910      40    NM
2    Margaret      F  1910      38    NM
3   Josephine      F  1910      35    NM
4       Helen      F  1910      26    NM
5     Juanita      F  1910      26    NM
6        Rosa      F  1910      20    NM
7     Frances      F  1910      19    NM
8        Emma      F  1910      18    NM
9        Ruth      F  1910      16    NM
10       Lucy      F  1910      15    NM
11      Irene      F  1910      14    NM
12     Isabel      F  1910      14    NM
13     Nellie      F  1910      14    NM
14      Alice      F  1910      13    NM
15      Julia      F  1910      13    NM
16      Marie      F  1910      13    NM
17       Rose      F  1910      13    NM
18      Anita      F  1910      12    NM
19       Anna      F  1910      12    NM
20   Beatrice      F  1910      12    NM
21     Jennie      F  1910      12    NM
22    Antonia      F  1910      11    NM
23    Dorothy      F  1910      11    NM
24        Eva      F  1910      11    NM
25      Hazel      F  1910      11    NM
26       Ruby      F  1910      11    NM
27     Elvira      F  1910      10    NM
28     Esther      F  1910      10    NM
29     Gladys      F  1910      10    NM

#### OR

Conditions must be on both sides of the or to eturn results in this case state = "NM" or state = "AZ" or state = "Texas".  Didn't show Tx, NM do to the limit 30 and conditon.

In [28]:
query = """
    SELECT name, gender, year, number, state
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE state = 'NM' OR state = 'AZ' OR state =  'TX'
    LIMIT 30
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 194,873,810 bytes (0.1949 GB)

         name gender  year  number state
0        Mary      F  1910      74    AZ
1       Maria      F  1910      29    AZ
2       Alice      F  1910      27    AZ
3    Margaret      F  1910      19    AZ
4       Helen      F  1910      18    AZ
5     Frances      F  1910      17    AZ
6     Dorothy      F  1910      16    AZ
7   Elizabeth      F  1910      15    AZ
8   Josephine      F  1910      15    AZ
9        Ruth      F  1910      15    AZ
10     Nellie      F  1910      14    AZ
11     Isabel      F  1910      12    AZ
12     Martha      F  1910      11    AZ
13      Betty      F  1910      10    AZ
14       Lucy      F  1910      10    AZ
15       Lupe      F  1910      10    AZ
16     Carmen      F  1910       9    AZ
17     Esther      F  1910       9    AZ
18      Grace      F  1910       9    AZ
19      Annie      F  1910       8    AZ
20     Bertha      F  1910       8    AZ
21        Eva      F  1910       8    AZ
22     Evelyn      F  1910       8    AZ
23      Julia      F  1910       8    AZ
24   Mercedes      F  1910       8    AZ
25    Pauline      F  1910       8    AZ
26       Rose      F  1910       8    AZ
27   Virginia      F  1910       8    AZ
28      Agnes      F  1910       7    AZ
29       Emma      F  1910       7    AZ

#### LIKE (with % or _ wildcard)

### Use LIKE AND % to find ny great grandmothers name

In [32]:
query = """
    SELECT name, gender, year, number, state
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE name LIKE 'Ursula%' AND state = 'NM'
    LIMIT 30
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 194,873,810 bytes (0.1949 GB)

      name gender  year  number state
0   Ursula      F  1918       5    NM
1   Ursula      F  1919       5    NM
2   Ursula      F  1930       5    NM
3   Ursula      F  1962       6    NM
4   Ursula      F  1968       5    NM
5   Ursula      F  1971       6    NM
6   Ursula      F  1973      10    NM
7   Ursula      F  1975       5    NM
8   Ursula      F  1978       6    NM
9   Ursula      F  1979       6    NM
10  Ursula      F  1981       6    NM
11  Ursula      F  1988       6    NM
12  Ursula      F  1990       5    NM

#### BETWEEN

Using Between for a range of dates from 1950 to 1969 - not dates returned on 1969 because of limit 30

In [34]:
query = """
    SELECT name, gender, year, number, state
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE year BETWEEN 1950 AND 1969
      AND state = 'NM'
    LIMIT 30
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 194,873,810 bytes (0.1949 GB)

         name gender  year  number state
0        Mary      F  1950     512    NM
1       Linda      F  1950     351    NM
2    Patricia      F  1950     243    NM
3     Barbara      F  1950     179    NM
4      Gloria      F  1950     159    NM
5    Margaret      F  1950     127    NM
6       Susan      F  1950     118    NM
7   Elizabeth      F  1950     117    NM
8       Maria      F  1950     112    NM
9       Nancy      F  1950     111    NM
10      Carol      F  1950     103    NM
11     Martha      F  1950     100    NM
12   Virginia      F  1950      98    NM
13    Deborah      F  1950      95    NM
14       Judy      F  1950      95    NM
15      Karen      F  1950      91    NM
16     Sandra      F  1950      86    NM
17      Betty      F  1950      83    NM
18      Donna      F  1950      81    NM
19      Irene      F  1950      81    NM
20     Sharon      F  1950      81    NM
21      Helen      F  1950      80    NM
22     Pamela      F  1950      78    NM
23    Dolores      F  1950      75    NM
24    Theresa      F  1950      73    NM
25    Frances      F  1950      72    NM
26       Rita      F  1950      70    NM
27    Shirley      F  1950      70    NM
28       Rose      F  1950      68    NM
29   Kathleen      F  1950      66    NM

#### LIMIT

### Limit 5

In [37]:
query = """
    SELECT name, gender, year, number, state
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE state = 'NM'
    LIMIT 5
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 194,873,810 bytes (0.1949 GB)

        name gender  year  number state
0       Mary      F  1910      98    NM
1      Maria      F  1910      40    NM
2   Margaret      F  1910      38    NM
3  Josephine      F  1910      35    NM
4      Helen      F  1910      26    NM

### Sorting and Grouping

#### ORDER BY

### Use order by desc and limit 30 to find the top 30 by count for year 1969 and can not use '1969' YEARS ARE INTS NOT STR

In [43]:
query = """
    SELECT name, gender, year, number, state
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE state = 'NM' AND year =1969
    ORDER BY number DESC
    LIMIT 30;
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 194,873,810 bytes (0.1949 GB)

           name gender  year  number state
0       Michael      M  1969     421    NM
1         David      M  1969     333    NM
2        Robert      M  1969     321    NM
3          John      M  1969     251    NM
4         James      M  1969     231    NM
5      Michelle      F  1969     225    NM
6          Lisa      F  1969     190    NM
7       Richard      M  1969     182    NM
8   Christopher      M  1969     161    NM
9        Joseph      M  1969     145    NM
10     Jennifer      F  1969     144    NM
11         Mark      M  1969     141    NM
12       Daniel      M  1969     134    NM
13      Melissa      F  1969     131    NM
14      Anthony      M  1969     129    NM
15         Paul      M  1969     128    NM
16      William      M  1969     125    NM
17       Steven      M  1969     121    NM
18     Patricia      F  1969     117    NM
19    Elizabeth      F  1969     117    NM
20      Charles      M  1969     110    NM
21        Brian      M  1969     107    NM
22      Patrick      M  1969     103    NM
23     Kimberly      F  1969     103    NM
24         Mary      F  1969      97    NM
25       Thomas      M  1969      94    NM
26        Kevin      M  1969      92    NM
27      Cynthia      F  1969      91    NM
28        Laura      F  1969      91    NM
29         Eric      M  1969      90    NM

#### DISTINCT

USE DISTINCT ON state and order by state as num_states to count how any distinct states = 51 states

In [44]:
query = """
    SELECT COUNT(DISTINCT state) AS num_states
    FROM `bigquery-public-data.usa_names.usa_1910_current`
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 25,246,016 bytes (0.0252 GB)

   num_states
0          51

#### GROUP BY

### Use group by to show TX, NM, and AZ with no limit condition

In [29]:
query = """
    SELECT state, COUNT(*) AS rows_per_state
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE state = 'NM' OR state = 'AZ' OR state = 'TX'
    GROUP BY state
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 25,246,016 bytes (0.0252 GB)

  state  rows_per_state
0    AZ          122085
1    NM           77755
2    TX          368987

### Aggregates

#### MAX

Use max for NM on biggest count in names

In [49]:
query = """
    SELECT MAX(number) AS biggest_count
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE state = 'NM'
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 75,738,048 bytes (0.0757 GB)

   biggest_count
0            589

uSE ORDER BY Dec, Limit 1 and result shows name plus count

In [47]:
query = """
    SELECT name, year, number, state
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE state = 'NM'
    ORDER BY number DESC
    LIMIT 1
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 175,939,298 bytes (0.1759 GB)

   name  year  number state
0  Mary  1947     589    NM

#### MIN

### Use Min on name to find the min name in NM

In [51]:
query = """
    SELECT MIN(name) AS smallest_count
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE state = 'NM'

"""
dry_run(query)
df = run_sql(query)
df

This query will scan 74,955,234 bytes (0.0750 GB)

  smallest_count
0          Aaden

### with order by ASC FOR NAME AND COUNT

In [52]:
query = """
    SELECT name, year, number, state
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE state = 'NM'
    ORDER BY number ASC
    LIMIT 1
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 175,939,298 bytes (0.1759 GB)

     name  year  number state
0  Aurora  1910       5    NM

#### SUM

### Returned total births since 1910 with names reproted more than five times.  So this is not the total of all births in NM names that were recorded once or twice are not listed in the totals/

In [53]:
query = """
    SELECT SUM(number) AS total_births
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE state = 'NM'
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 75,738,048 bytes (0.0757 GB)

   total_births
0       1752061

#### AVG

### Looking at average births per year using order by, and group byt

In [54]:
query = """
    SELECT year, AVG(number) AS avg_births
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE state = 'NM' AND year BETWEEN 1910 AND 1939
    GROUP BY year
    ORDER BY year
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 126,230,080 bytes (0.1262 GB)

    year  avg_births
0   1910   11.561151
1   1911   11.071429
2   1912   12.381818
3   1913   12.751092
4   1914   13.823970
5   1915   15.174286
6   1916   16.101408
7   1917   15.386139
8   1918   17.191283
9   1919   16.309645
10  1920   17.661939
11  1921   18.134228
12  1922   17.875269
13  1923   17.522678
14  1924   18.032751
15  1925   17.479915
16  1926   17.431818
17  1927   17.437500
18  1928   18.012397
19  1929   17.817410
20  1930   18.563525
21  1931   18.641975
22  1932   18.491228
23  1933   18.017857
24  1934   19.037255
25  1935   19.822134
26  1936   19.851190
27  1937   20.075646
28  1938   20.547619
29  1939   21.131679

#### COUNT

Use count to total all births in 1969 that were male

In [55]:
query = """
    SELECT SUM(number) AS total_male_births
    FROM `bigquery-public-data.usa_names.usa_1910_current`
    WHERE state = 'NM' AND gender = 'M' AND year = 1969
"""
dry_run(query)
df = run_sql(query)
df

This query will scan 145,164,592 bytes (0.1452 GB)

   total_male_births
0               9295

## Make some plots

Make some cool plots to go with your data. Write SQL queries to get ONLY the information you need for each plot. (Don't pull ALL the data and then just plot a few columns.)

## EXTRA CREDIT:

#### Use a query that joins two tables.

#### Make a model to see if you can predict something

#### Come up with something else cool to do with your data