<a href="https://colab.research.google.com/github/cyeef/Data-Science-Portfolio-C21-/blob/main/Exercises/Vincent-Data-Index-Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment

Pull data using the following link https://vincentarelbundock.github.io/Rdatasets/datasets.html  and determine what is there.

**That is, using the above URL, answer the following:**


1.  how many data sets are there?
2.  how many data sets are accessible, i.e. can be read by Pandas?

**According to Pandas.**

3.  how many rows are in each data set?
4.  how many columns are in each data set?
5.  what are the data types of each column in each data set?
6.   how many columns have nulls?
7.   how many rows have nulls?

Explore Data set

In [2]:
import pandas as pd
from rich import print  # print("This is [bold]bold text[/bold] and this is normal.")
index = pd.read_csv('https://vincentarelbundock.github.io/Rdatasets/datasets.csv')


print('[bold]Total number of data sets in the Vincent repository[/bold]', len(index))  # use length function to determine the total data sets.

Total number of data sets in the Vincent repository 3648

In [5]:
index.shape

(3648, 12)

In [8]:
len(index) #how many data sets are there?  3648 datasets exist in the catalog

3648

In [10]:
print(type(index))

<class 'pandas.core.frame.DataFrame'>

In [11]:
index.head()

,Package,Item,Title,Rows,Cols,n_binary,n_character,n_factor,n_logical,n_numeric,CSV,Doc
0,admiral,admiral_adlb,Lab Analysis Dataset,330,115,13,79,0,0,25,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...
1,admiral,admiral_adsl,Subject Level Analysis Dataset,306,54,5,39,0,0,5,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...
2,admiral,atoxgr_criteria_ctcv4,Metadata Holding Grading Criteria for NCI-CTCA...,42,13,2,13,0,0,0,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...
3,admiral,atoxgr_criteria_ctcv4_uscv,Metadata Holding Grading Criteria for NCI-CTCA...,48,13,2,13,0,0,0,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...
4,admiral,atoxgr_criteria_ctcv5,Metadata Holding Grading Criteria for NCI-CTCA...,40,13,2,13,0,0,0,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...

In [40]:
accessible = 0           #how many data sets are accessible, i.e. can be read by Pandas?  Readable 3631 and 17 not accessible
                         # used accessible = [] and accessible = += 1 is a mismatch and will result in a empty list
for index_num, row in index.iterrows():
  try:  # try catch on error
    df = pd.read_csv(row["CSV"])   #fetches file to read
    accessible += 1 # adds one to [] list
  except Exception as unreadble:  # continues thru the loop without error
    pass
print("Accessible", accessible)

/tmp/ipykernel_2000/244132464.py:5: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])   #fetches file to read
/tmp/ipykernel_2000/244132464.py:5: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])   #fetches file to read
/tmp/ipykernel_2000/244132464.py:5: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])   #fetches file to read
/tmp/ipykernel_2000/244132464.py:5: DtypeWarning: Columns (13,15,17,18,20,52,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])   #fetches file to read
/tmp/ipykernel_2000/244132464.py:5: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])   #fetches file to read
/tmp/ipykernel_2000/244132464.py:5: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58,94) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])   #fetches file to read

Accessible 3631

In [ ]:
for index_num, row in index.iterrows():   #  how many rows are in each data set? Did save the total
    try:
        df = pd.read_csv(row["CSV"])
        print(row["Item"], "has", df.shape[0], "rows")
    except Exception as e:
        pass

In [42]:
row_counts = []   # empty list to collect results  #Number of results: 3631
                                                   #First 10 row counts:
for index_num, row in index.iterrows():            #[330, 306, 42, 48, 40, 46, 43, 48, 63, 71]
    try:
        df = pd.read_csv(row["CSV"])
        row_counts.append(df.shape[0])   # add this dataset's row count to the list
    except Exception as e:
        pass

print("Number of results:", len(row_counts))
print("First 10 row counts:", row_counts[:10])

/tmp/ipykernel_2000/2809099397.py:5: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/2809099397.py:5: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/2809099397.py:5: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/2809099397.py:5: DtypeWarning: Columns (13,15,17,18,20,52,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/2809099397.py:5: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/2809099397.py:5: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58,94) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])

Number of results: 3631

First 10 row counts:
[330, 306, 42, 48, 40, 46, 43, 48, 63, 71]

In [45]:
col_counts = []   # empty list to collect each dataset's column count

for index_num, row in index.iterrows():
    try:
        df = pd.read_csv(row["CSV"])
        col_counts.append(df.shape[1])   # [1] = columns, not rows
    except Exception as e:
        pass

print("Number of results:", len(col_counts))
print("First 10 column counts:", col_counts[:10])

/tmp/ipykernel_2000/975441975.py:5: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/975441975.py:5: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/975441975.py:5: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/975441975.py:5: DtypeWarning: Columns (13,15,17,18,20,52,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/975441975.py:5: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/975441975.py:5: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58,94) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])

Number of results: 3631

First 10 column counts:
[116, 55, 14, 14, 14, 14, 14, 14, 15, 15]

In [47]:
for index_num, row in index.iterrows():
    try:
        df = pd.read_csv(row["CSV"])
        print(row["Item"], "dtypes:")
        print(df.dtypes)
        break
    except Exception as e:
        pass

admiral_adlb dtypes:

rownames      int64
STUDYID      object
DOMAIN       object
USUBJID      object
LBSEQ         int64
             ...
REGION1     float64
LDDTHGR1    float64
DTH30FL     float64
DTHA30FL    float64
DTHB30FL    float64
Length: 116, dtype: object

In [49]:
dtype_summaries = []   # what are the data types of each column in each data set?  data set is mixed with various dTYPES:

for index_num, row in index.iterrows():
    try:
        df = pd.read_csv(row["CSV"])
        counts = df.dtypes.astype(str).value_counts()
        dtype_summaries.append({
            "dataset": row["Item"],
            "int_cols": int(counts.get("int64", 0)),
            "float_cols": int(counts.get("float64", 0)),
            "object_cols": int(counts.get("object", 0)),
        })
    except Exception as e:
        pass

print("number of datasets summarized:", len(dtype_summaries))
print(dtype_summaries[:5])   # peek at the first 5

/tmp/ipykernel_2000/3438499605.py:5: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/3438499605.py:5: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/3438499605.py:5: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/3438499605.py:5: DtypeWarning: Columns (13,15,17,18,20,52,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/3438499605.py:5: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/3438499605.py:5: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58,94) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])

number of datasets summarized: 3631

[
    {'dataset': 'admiral_adlb', 'int_cols': 19, 'float_cols': 36, 'object_cols': 61},
    {'dataset': 'admiral_adsl', 'int_cols': 4, 'float_cols': 8, 'object_cols': 43},
    {'dataset': 'atoxgr_criteria_ctcv4', 'int_cols': 1, 'float_cols': 0, 'object_cols': 13},
    {'dataset': 'atoxgr_criteria_ctcv4_uscv', 'int_cols': 1, 'float_cols': 0, 'object_cols': 13},
    {'dataset': 'atoxgr_criteria_ctcv5', 'int_cols': 1, 'float_cols': 0, 'object_cols': 13}
]

In [7]:
index.info()   # what are the data types of each column in each data set?

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3648 entries, 0 to 3647
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Package      3648 non-null   object
 1   Item         3648 non-null   object
 2   Title        3648 non-null   object
 3   Rows         3648 non-null   int64
 4   Cols         3648 non-null   int64
 5   n_binary     3648 non-null   int64
 6   n_character  3648 non-null   int64
 7   n_factor     3648 non-null   int64
 8   n_logical    3648 non-null   int64
 9   n_numeric    3648 non-null   int64
 10  CSV          3648 non-null   object
 11  Doc          3648 non-null   object
dtypes: int64(7), object(5)
memory usage: 342.1+ KB

In [51]:
def null_cols_for(csv_url):    #null count for cols
    try:
        df = pd.read_csv(csv_url)
        return (df.isnull().sum() > 0).sum()
    except Exception:
        return None  # report none if error
null_col_counts = [null_cols_for(url) for url in index["CSV"]]

/tmp/ipykernel_2000/1631939756.py:3: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_url)
/tmp/ipykernel_2000/1631939756.py:3: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_url)
/tmp/ipykernel_2000/1631939756.py:3: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_url)
/tmp/ipykernel_2000/1631939756.py:3: DtypeWarning: Columns (13,15,17,18,20,52,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_url)
/tmp/ipykernel_2000/1631939756.py:3: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_url)
/tmp/ipykernel_2000/1631939756.py:3: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58,94) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_url)

In [55]:
print(clean_counts[:20])          # how many datasets have AT LEAST ONE null column 878
print(max(clean_counts))
print(sum(1 for c in clean_counts if c > 0))

[
    np.int64(31),
    np.int64(34),
    np.int64(2),
    np.int64(2),
    np.int64(2),
    np.int64(2),
    np.int64(4),
    np.int64(4),
    np.int64(9),
    np.int64(9),
    np.int64(0),
    np.int64(0),
    np.int64(2),
    np.int64(5),
    np.int64(4),
    np.int64(0),
    np.int64(0),
    np.int64(0),
    np.int64(3),
    np.int64(0)
]

748

878

In [60]:
clean_counts = [c for c in null_col_counts if c is not None]
print("datasets summarized:", len(clean_counts))

datasets summarized: 3631

In [56]:
count = 0
for c in clean_counts:
    if c > 0:
        count = count + 1

print(count)   # 878 columns have nulls

878

In [58]:
#how many rows have nulls?
def null_rows_for(csv_url):    #null count for rows
    try:
        df = pd.read_csv(csv_url)
        return df.isnull().any(axis=1).sum()
    except Exception:
        return None  # report none if error
null_rows_counts = [null_rows_for(url) for url in index["CSV"]]

/tmp/ipykernel_2000/83620284.py:4: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_url)
/tmp/ipykernel_2000/83620284.py:4: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_url)
/tmp/ipykernel_2000/83620284.py:4: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_url)
/tmp/ipykernel_2000/83620284.py:4: DtypeWarning: Columns (13,15,17,18,20,52,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_url)
/tmp/ipykernel_2000/83620284.py:4: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_url)
/tmp/ipykernel_2000/83620284.py:4: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58,94) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_url)

In [59]:
clean_row_counts = [c for c in null_rows_counts if c is not None]
print(clean_row_counts[:20])
print(max(clean_row_counts))
print(sum(1 for c in clean_row_counts if c > 0))

[
    np.int64(330),
    np.int64(306),
    np.int64(34),
    np.int64(34),
    np.int64(34),
    np.int64(34),
    np.int64(36),
    np.int64(36),
    np.int64(63),
    np.int64(68),
    np.int64(0),
    np.int64(0),
    np.int64(2),
    np.int64(15),
    np.int64(14),
    np.int64(0),
    np.int64(0),
    np.int64(0),
    np.int64(3),
    np.int64(0)
]

177960

878

In [66]:
print("length of index:", len(index))
print("length of null_rows_counts:", len(null_rows_counts))

length of index: 3648

length of null_rows_counts: 3648

In [67]:
clean_row_counts = [c for c in null_rows_counts if c is not None]
print("datasets with at least one row containing nulls:", sum(1 for c in clean_row_counts if c > 0))
print("TOTAL rows-with-nulls, summed across the whole catalog:", sum(clean_row_counts))

datasets with at least one row containing nulls: 878

TOTAL rows-with-nulls, summed across the whole catalog: 2231682

In [54]:
for index_num, row in sample.iterrows():  # mixed data types
    try:
        df = pd.read_csv(row["CSV"])
        counts = df.dtypes.astype(str).value_counts()
        print(row["Item"], "-> int:", counts.get("int64",0),
              "float:", counts.get("float64",0),
              "object:", counts.get("object",0))
    except Exception as e:
        print(row["Item"], "failed:", e)

bachelorette -> int: 2 float: 20 object: 2

jtrain2 -> int: 14 float: 6 object: 0

wagepan -> int: 44 float: 1 object: 0

wvs_ccodes -> int: 2 float: 1 object: 1

WalkingBabies -> int: 1 float: 1 object: 1

In [33]:
list(index.itertuples())[0]  # → a tuple:  Pandas(Index=0, Package='AER', Item='Affairs', ...)

Pandas(Index=0, Package='admiral', Item='admiral_adlb', Title='Lab Analysis Dataset', Rows=330, Cols=115, n_binary=13, n_character=79, n_factor=0, n_logical=0, n_numeric=25, CSV='https://vincentarelbundock.github.io/Rdatasets/csv/admiral/admiral_adlb.csv', Doc='https://vincentarelbundock.github.io/Rdatasets/doc/admiral/admiral_adlb.html')

In [36]:
list(index.iterrows())[0]   # → different shape: (0, Package AER  Item Affairs ...)  — a tuple containing a Series

(0,
 Package                                                  admiral
 Item                                                admiral_adlb
 Title                                       Lab Analysis Dataset
 Rows                                                         330
 Cols                                                         115
 n_binary                                                      13
 n_character                                                   79
 n_factor                                                       0
 n_logical                                                      0
 n_numeric                                                     25
 CSV            https://vincentarelbundock.github.io/Rdatasets...
 Doc            https://vincentarelbundock.github.io/Rdatasets...
 Name: 0, dtype: object)

In [18]:
index.to_dict('records')[0]           # → a dict:  {'Package': 'AER', 'Item': 'Affairs', ...}

{'Package': 'admiral',
 'Item': 'admiral_adlb',
 'Title': 'Lab Analysis Dataset',
 'Rows': 330,
 'Cols': 115,
 'n_binary': 13,
 'n_character': 79,
 'n_factor': 0,
 'n_logical': 0,
 'n_numeric': 25,
 'CSV': 'https://vincentarelbundock.github.io/Rdatasets/csv/admiral/admiral_adlb.csv',
 'Doc': 'https://vincentarelbundock.github.io/Rdatasets/doc/admiral/admiral_adlb.html'}

In [28]:
index.iterrows()

In [29]:
for index_num, row in index.iterrows():
  print(index_num)
  print(row)
  break

0

Package                                                  admiral
Item                                                admiral_adlb
Title                                       Lab Analysis Dataset
Rows                                                         330
Cols                                                         115
n_binary                                                      13
n_character                                                   79
n_factor                                                       0
n_logical                                                      0
n_numeric                                                     25
CSV            https://vincentarelbundock.github.io/Rdatasets...
Doc            https://vincentarelbundock.github.io/Rdatasets...
Name: 0, dtype: object

In [30]:
for row in index.itertuples():
    print(type(row))
    break

<class 'pandas.core.frame.Pandas'>

  Code using a heartbeat if statement in the first for loop, the second one does not have the heartbeat, both have try and except blocks in case of error(s) allowing for coninued iterations - some datasets may not be accessible.

 DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.  This read correctly.

**Total datasets:** 3648

**Accessible (readable by Pandas):** 3631

**Failed:** 17

1.  book_banning → UnicodeDecodeError   = file downloaded but has non-UTF-8 characters (recoverable with encoding="latin-1")


2.  georgia_sf → HTTPError  = file unavailable/not a flat CSV (often _sf   spatial objects)

3.  nz_murders_sf → HTTPError  = file unavailable/not a flat CSV (often _sf spatial objects)

4.  sentencing_sf → HTTPError  = file unavailable/not a flat CSV (often _sf spatial objects)

5.  co2 → HTTPError Access failure  = file unavailable/not a flat CSV

6.  ahca_polls → UnicodeDecodeError = file downloaded but has non-UTF-8 characters (recoverable with encoding="latin-1")

7.  avengers → UnicodeDecodeError = file downloaded but has non-UTF-8 characters (recoverable with encoding="latin-1")

8.  biopics → UnicodeDecodeError = file downloaded but has non-UTF-8 characters (recoverable with encoding="latin-1")

9.  cand_events_20150130 → UnicodeDecodeError = file downloaded but has non-UTF-8 characters (recoverable with encoding="latin-1")

10. hiphop_cand_lyrics → UnicodeDecodeError = file downloaded but has non-UTF-8 characters (recoverable with encoding="latin-1")


11. mad_men → UnicodeDecodeError = file downloaded but has non-UTF-8 characters (recoverable with encoding="latin-1")


12. police_killings → UnicodeDecodeError = file downloaded but has non-UTF-8 characters (recoverable with encoding="latin-1")


13. tenth_circuit → UnicodeDecodeError = file downloaded but has non-UTF-8 characters (recoverable with encoding="latin-1")


14. VALungCancer_list → HTTPError = 404


15. nyc → UnicodeDecodeError = file downloaded but has non-UTF-8 characters (recoverable with encoding="latin-1")


16. ts → UnicodeDecodeError = file downloaded but has non-UTF-8 characters (recoverable with encoding="latin-1")


17. UScitiesD_dist → HTTPError = file unavailable/not a flat CSV (often _sf spatial objects)

In [ ]:
# --- reset counters before the loop (run this every time) ---
accessible = 0
failed = []

# --- new version with heartbeat ---
for i, (_, row) in enumerate(index.iterrows()):
    if i % 250 == 0:                          # heartbeat: every 250th dataset
        print(f"checked {i} so far...")
    try:
        df = pd.read_csv(row["CSV"])          # try to open it
        accessible += 1                        # success → tally one accessible
    except Exception as e:                     # catch any read failure
        failed.append((row["Item"], type(e).__name__))  # store (name, error type)

print("Total datasets:", len(index))
print("Accessible (readable by Pandas):", accessible)
print("Failed:", len(failed))
for name, err in failed:
    print("   ✗", name, "→", err)

checked 0 so far...

checked 250 so far...

checked 500 so far...

checked 750 so far...

checked 1000 so far...

checked 1250 so far...

checked 1500 so far...

checked 1750 so far...

checked 2000 so far...

checked 2250 so far...

checked 2500 so far...

/tmp/ipykernel_25247/2498590004.py:10: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])          # try to open it
/tmp/ipykernel_25247/2498590004.py:10: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])          # try to open it
/tmp/ipykernel_25247/2498590004.py:10: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])          # try to open it
/tmp/ipykernel_25247/2498590004.py:10: DtypeWarning: Columns (13,15,17,18,20,52,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])          # try to open it
/tmp/ipykernel_25247/2498590004.py:10: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])          # try to open it
/tmp/ipykernel_25247/2498590004.py:10: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58,94) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])          # try to open it

checked 2750 so far...

checked 3000 so far...

checked 3250 so far...

checked 3500 so far...

Total datasets: 3648

Accessible (readable by Pandas): 3631

Failed: 17

   ✗ book_banning → UnicodeDecodeError

   ✗ georgia_sf → HTTPError

   ✗ nz_murders_sf → HTTPError

   ✗ sentencing_sf → HTTPError

   ✗ co2 → HTTPError

   ✗ ahca_polls → UnicodeDecodeError

   ✗ avengers → UnicodeDecodeError

   ✗ biopics → UnicodeDecodeError

   ✗ cand_events_20150130 → UnicodeDecodeError

   ✗ hiphop_cand_lyrics → UnicodeDecodeError

   ✗ mad_men → UnicodeDecodeError

   ✗ police_killings → UnicodeDecodeError

   ✗ tenth_circuit → UnicodeDecodeError

   ✗ VALungCancer_list → HTTPError

   ✗ nyc → UnicodeDecodeError

   ✗ ts → UnicodeDecodeError

   ✗ UScitiesD_dist → HTTPError

Use for loop to enumerate shape, data type, and null counts

In [62]:
records = []
for i, (_, row) in enumerate(index.iterrows()):
    if i % 250 == 0:
        print(f"checked {i}...")
    try:
        df = pd.read_csv(row["CSV"])
        dt = df.dtypes.astype(str).value_counts()      # cast to str so .get works
        records.append({
            "dataset": f"{row['Package']}/{row['Item']}",
            "rows": df.shape[0],
            "columns": df.shape[1],
            "int_cols": int(dt.get("int64", 0)),
            "float_cols": int(dt.get("float64", 0)),
            "object_cols": int(dt.get("object", 0)),
            "cols_with_nulls": int((df.isnull().sum() > 0).sum()),
            "rows_with_nulls": int(df.isnull().any(axis=1).sum()),
            "readable": True,
        })
    except Exception as e:
        records.append({"dataset": f"{row['Package']}/{row['Item']}",
                        "readable": False, "error": type(e).__name__})

profile = pd.DataFrame(records)
profile.to_csv("rdatasets_profile.csv", index=False)   # save it once; it took minutes to build
profile.head(20)

checked 0...

checked 250...

checked 500...

checked 750...

checked 1000...

checked 1250...

checked 1500...

checked 1750...

checked 2000...

checked 2250...

checked 2500...

/tmp/ipykernel_2000/2101663543.py:6: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/2101663543.py:6: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/2101663543.py:6: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/2101663543.py:6: DtypeWarning: Columns (13,15,17,18,20,52,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/2101663543.py:6: DtypeWarning: Columns (14,16,18,19,21,22,53,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])
/tmp/ipykernel_2000/2101663543.py:6: DtypeWarning: Columns (13,14,16,18,19,21,22,55,57,58,94) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(row["CSV"])

checked 2750...

checked 3000...

checked 3250...

checked 3500...

,dataset,rows,columns,int_cols,float_cols,object_cols,cols_with_nulls,rows_with_nulls,readable,error
0,admiral/admiral_adlb,330.0,116.0,19.0,36.0,61.0,31.0,330.0,True,NaN
1,admiral/admiral_adsl,306.0,55.0,4.0,8.0,43.0,34.0,306.0,True,NaN
2,admiral/atoxgr_criteria_ctcv4,42.0,14.0,1.0,0.0,13.0,2.0,34.0,True,NaN
3,admiral/atoxgr_criteria_ctcv4_uscv,48.0,14.0,1.0,0.0,13.0,2.0,34.0,True,NaN
4,admiral/atoxgr_criteria_ctcv5,40.0,14.0,1.0,0.0,13.0,2.0,34.0,True,NaN
5,admiral/atoxgr_criteria_ctcv5_uscv,46.0,14.0,1.0,0.0,13.0,2.0,34.0,True,NaN
6,admiral/atoxgr_criteria_ctcv6,43.0,14.0,1.0,0.0,13.0,4.0,36.0,True,NaN
7,admiral/atoxgr_criteria_ctcv6_uscv,48.0,14.0,1.0,0.0,13.0,4.0,36.0,True,NaN
8,admiral/atoxgr_criteria_daids,63.0,15.0,1.0,0.0,14.0,9.0,63.0,True,NaN
9,admiral/atoxgr_criteria_daids_uscv,71.0,15.0,1.0,0.0,14.0,9.0,68.0,True,NaN
10,admiral/country_code_lookup,249.0,4.0,2.0,0.0,2.0,0.0,0.0,True,NaN
11,admiral/dose_freq_lookup,86.0,6.0,1.0,2.0,3.0,0.0,0.0,True,NaN
12,admiral/example_qs,161.0,12.0,3.0,1.0,8.0,2.0,2.0,True,NaN
13,admiral/queries,15.0,9.0,1.0,3.0,5.0,5.0,15.0,True,NaN
14,admiral/queries_mh,14.0,9.0,1.0,3.0,5.0,4.0,14.0,True,NaN
15,AER/Affairs,601.0,10.0,6.0,2.0,2.0,0.0,0.0,True,NaN
16,AER/ArgentinaCPI,80.0,3.0,1.0,2.0,0.0,0.0,0.0,True,NaN
17,AER/BankWages,474.0,5.0,2.0,0.0,3.0,0.0,0.0,True,NaN
18,AER/BenderlyZwick,31.0,6.0,1.0,5.0,0.0,3.0,3.0,True,NaN
19,AER/BondYield,60.0,3.0,1.0,2.0,0.0,0.0,0.0,True,NaN

Confirming out puts from above.

In [63]:
print("Total datasets:", len(profile))
print("Accessible:",(profile["readable"].sum()))
print("Failed:", (~profile["readable"]).sum())  #~ is the "not" operator for True/False

Total datasets: 3648

Accessible: 3631

Failed: 17

Will comment out this loop and try a heartbeat loop - above - does the same thing just indicates where the loop is in the iteration.

In [ ]:
"""
accessible = 0 # count starts at zero
failed = []  # keeping track of failed reads in the data set with a list

for _, row in index.iterrows():   # for loop
    try:  # try to read the dataset
        df = pd.read_csv(row["CSV"])   # try to open it
        accessible += 1  # if readable add 1 to accessible
    except Exception as e:             # catch anything that breaks
        failed.append((row["Item"], type(e).__name__))  # append list failed [] with name

print("Total datasets:", len(index))        # print number of datasets should equal 3648
print("Accessible (readable by Pandas):", accessible)  # print number of accessible datasets
print("Failed:", len(failed))   # print failed reads
for name, err in failed:           # loop and print name and error
    print("   ✗", name, "→", err)
"""

'\naccessible = 0 # count starts at zero \nfailed = []  # keeping track of failed reads in the data set with a list \n\nfor _, row in index.iterrows():   # for loop \n    try:  # try to read the dataset \n        df = pd.read_csv(row["CSV"])   # try to open it\n        accessible += 1  # if readable add 1 to accessible \n    except Exception as e:             # catch anything that breaks\n        failed.append((row["Item"], type(e).__name__))  # append list failed [] with name \n\nprint("Total datasets:", len(index))        # print number of datasets should equal 3648\nprint("Accessible (readable by Pandas):", accessible)  # print number of accessible datasets\nprint("Failed:", len(failed))   # print failed reads\nfor name, err in failed:           # loop and print name and error \n    print("   ✗", name, "→", err)\n'